# Generated by Django 4.0.2 on 2022-02-22 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipaatar', '0002_multiplechoiceanswer_question_survey_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAccessed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField()),
                ('goalMet', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BPGoal',
            fields=[
                ('goal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hipaatar.goal')),
                ('startSysBP', models.IntegerField()),
                ('goalSysBP', models.IntegerField()),
                ('startDiaBP', models.IntegerField()),
                ('goalDiaBP', models.IntegerField()),
            ],
            bases=('hipaatar.goal',),
        ),
        migrations.CreateModel(
            name='WeightGoal',
            fields=[
                ('goal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hipaatar.goal')),
                ('startWeight', models.IntegerField()),
                ('goalWeight', models.IntegerField()),
            ],
            bases=('hipaatar.goal',),
        ),
    ]
