# Generated by Django 4.0.3 on 2022-04-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_healthgoal_date_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthgoal',
            name='goal_date',
        ),
    ]
